name: import_element
author: Günter Zöchbauer <guenter@gzoechbauer.com>
description: "solved: Import a polymer element in markup and code \nhttps://code.google.com/p/dart/issues/detail?id=15953"
dependencies:
  browser: any
  polymer: any

transformers:
- polymer:
    entry_points: [web/index.html]
